### ISSUE TITLE
QC checks

### ISSUE THREAD

**Issue by s-lavoie** [aigoyal/EPItome-xl#9]
When I run the preprocessing pipeline, I requested all available qc checks. The files that are produced are unable to open.

**Comment by josephdviviano** [comment]
Without an error message this is hard to guess at. But try this:

    rm ~/.ICEauthority

then re-run your QCs one-by-one. Report any errors here.

Also, I think the `spectra` qc is broken. I might have turned it into madness :D

**Comment by s-lavoie** [comment]
Hello, I just met with Aman to ensure I was running everything correctly before posting the error message. I ran the command Joe suggested and then ran the qc checks individually. The same problem with the files not opening correctly.

This is what I ran:
python /home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_EPI2T1 /srv/MRI/WORKING BEBASD TASK

This was the error message:
++ 3dedge3: AFNI version=AFNI_2011_12_21_1014 (Mar 21 2014) [64-bit]
** ERROR: can't open dataset (null)
Traceback (most recent call last):
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_EPI2T1", line 146, in <module>
    reg_check(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_EPI2T1", line 52, in reg_check
    edge = nib.load(edge).get_data()
  File "/usr/lib/pymodules/python2.7/nibabel/loadsave.py", line 54, in load
    return klass.from_filename(filename)
  File "/usr/lib/pymodules/python2.7/nibabel/spatialimages.py", line 411, in from_filename
    return klass.from_file_map(file_map)
  File "/usr/lib/pymodules/python2.7/nibabel/analyze.py", line 869, in from_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='rb')
  File "/usr/lib/pymodules/python2.7/nibabel/fileholders.py", line 69, in get_prepare_fileobj
    obj = allopen(self.filename, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/nibabel/volumeutils.py", line 1284, in allopen
    return opener(fname, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/old_grp_masks/T1/SESS01/anat_T1_edge.nii.gz'

**Comment by josephdviviano** [comment]
Hi Steph, can you confirm that all of your input files are OK? It is complaining that your inputs are bad (this thing works on your anat_T1_XXX.nii.gz files).

**Comment by s-lavoie** [comment]
Hi Joe,

It seems be trying to run it on participants that I don't want to include, because they are in the working directory. It tries to run it on all directories even directories that are not participants, so they wouldn't have input files. I tried to make a new directory with just the participants and the pipeline scripts to see if that would work, but now it seems to be even worse. It is still trying to run it on all directories in the BEBASD directory.

**Comment by josephdviviano** [comment]
The only folders in the experiment directory should be subject directories. If you want to keep other files around you need to put them somewhere else.

**Comment by s-lavoie** [comment]
Ok, I moved all other directories

and now here are the errors I am getting (I listed them with many spaces in between as the errors were very spread out):

 3dMean: AFNI version=AFNI_2011_12_21_1014 (Mar 21 2014) [64-bit]
** ERROR: dataset /srv/MRI/WORKING/BEBASD/220/TASK/SESS01/anat_EPI_mask_MNI.nii.gz doesn't match /srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_EPI_mask_MNI.nii.gz sizes
** I'm telling your mother about this!
++ 3dcalc: AFNI version=AFNI_2011_12_21_1014 (Mar 21 2014) [64-bit]
++ Authored by: A cast of thousands
** FATAL ERROR: can't open dataset /srv/MRI/WORKING/BEBASD/tmp_mean.nii.gz
** Program compile date = Mar 21 2014
rm: cannot remove `/srv/MRI/WORKING/BEBASD/tmp_mean.nii.gz': No such file or directory




ICE default IO error handler doing an exit(), pid = 25869, errno = 32




IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/220/TASK/SESS01/func_ob.SL_DISS_FEB26.01.nii.gz'




IOError: /srv/MRI/WORKING/BEBASD/220/TASK/SESS01/PARAMS/motion.SL_DISS_FEB26.01.1D not found.
Generating 4D file dimensions for BEBASD
ls: cannot access /srv/MRI/WORKING/BEBASD/201//old_pipelinefile//*/: No such file or directory
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
Wrote data to /srv/MRI/WORKING/BEBASD/raw_NIFTI_overview.csv
Traceback (most recent call last):
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 353, in <module>
    regressor_spectra(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 251, in regressor_spectra
    'anat_gm.nii.gz'))
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 45, in load_mask
    mask = nib.load(path).get_data()
  File "/usr/lib/pymodules/python2.7/nibabel/loadsave.py", line 54, in load
    return klass.from_filename(filename)
  File "/usr/lib/pymodules/python2.7/nibabel/spatialimages.py", line 411, in from_filename
    return klass.from_file_map(file_map)
  File "/usr/lib/pymodules/python2.7/nibabel/analyze.py", line 869, in from_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='rb')
  File "/usr/lib/pymodules/python2.7/nibabel/fileholders.py", line 69, in get_prepare_fileobj
    obj = allopen(self.filename, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/nibabel/volumeutils.py", line 1284, in allopen
    return opener(fname, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_gm.nii.gz'

**Comment by josephdviviano** [comment]
This seems impossible, I think you made some mistakes when you were manually moving files around

      ERROR: dataset /srv/MRI/WORKING/BEBASD/220/TASK/SESS01/anat_EPI_mask_MNI.nii.gz doesn't match /srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_EPI_mask_MNI.nii.gz sizes

Anyways this is an @aigoyal problem, can he deal with it?

**Comment by josephdviviano** [comment]
You don't really need this QC to work anyhow... you could do it by eye.

**Comment by s-lavoie** [comment]
I think I figured out that error. I hadn't run 220 through the same pipeline because I wasn't going to include them in my dissertation. Will fix this error and report back

**Comment by s-lavoie** [comment]
Hello again,

Ok, so now many of the above errors were corrected, but it is still not working:

 File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_masks", line 211, in <module>
    mask_check(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_masks", line 58, in mask_check
    wm = nib.load(wm).get_data()
  File "/usr/lib/pymodules/python2.7/nibabel/loadsave.py", line 54, in load
    return klass.from_filename(filename)
  File "/usr/lib/pymodules/python2.7/nibabel/spatialimages.py", line 411, in from_filename
    return klass.from_file_map(file_map)
  File "/usr/lib/pymodules/python2.7/nibabel/analyze.py", line 869, in from_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='rb')
  File "/usr/lib/pymodules/python2.7/nibabel/fileholders.py", line 69, in get_prepare_fileobj
    obj = allopen(self.filename, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/nibabel/volumeutils.py", line 1284, in allopen
    return opener(fname, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_wm_ero.nii.gz'
Traceback (most recent call last):
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_motionind", line 301, in <module>
    individual_motion_plot(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_motionind", line 125, in individual_motion_plot
    '.1D'), head_r)      
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_motionind", line 54, in compute_FD
    f = np.genfromtxt(f)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1333, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 147, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 496, in open
    raise IOError("%s not found." % path)
IOError: /srv/MRI/WORKING/BEBASD/226/TASK/SESS01/PARAMS/motion.SL_DISS_FEB26.06.1D not found.
Generating 4D file dimensions for BEBASD
ls: cannot access /srv/MRI/WORKING/BEBASD/201//old_pipelinefile//*/: No such file or directory
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
Wrote data to /srv/MRI/WORKING/BEBASD/raw_NIFTI_overview.csv
Traceback (most recent call last):
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 353, in <module>
    regressor_spectra(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 251, in regressor_spectra
    'anat_gm.nii.gz'))
  File "/home/sbrown/EPItome-xl/SL_DISS_FEB26//epitome/modules/qc/check_spectra", line 45, in load_mask
    mask = nib.load(path).get_data()
  File "/usr/lib/pymodules/python2.7/nibabel/loadsave.py", line 54, in load
    return klass.from_filename(filename)
  File "/usr/lib/pymodules/python2.7/nibabel/spatialimages.py", line 411, in from_filename
    return klass.from_file_map(file_map)
  File "/usr/lib/pymodules/python2.7/nibabel/analyze.py", line 869, in from_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='rb')
  File "/usr/lib/pymodules/python2.7/nibabel/fileholders.py", line 69, in get_prepare_fileobj
    obj = allopen(self.filename, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/nibabel/volumeutils.py", line 1284, in allopen
    return opener(fname, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_gm.nii.gz'

**Comment by s-lavoie** [comment]
sorry another update:

the qc_mc_TR, qc_reg_T1_to_MNI, and qc_TASK_SL_DISS_FEB26_regressor_spectra now open

the qc_reg_EPI_to_T1 opens, but looks ridiculous (not sure if this is my data or not- more of a question for Aman I think)

the motion and the masks are still not working

**Comment by josephdviviano** [comment]
I think you should maybe start again with this data (just use `epitome clean`) and not move files and folders around. At this point no one could really tell you what has happened to your data.

**Comment by s-lavoie** [comment]
I didn't move specific files around, just participant directories. I had created one directory in my working directory for dissertation participants and another for unneeded participants. When you indicated it can't work that way, I move the entire unneeded participants out of the working directory and all dissertation participants out of the "dissertation participants" sub directory and into my working directory. I do not understand how that would have caused any problems. 

Aman had also created two directories to store old scripts and group masks. I have since also removed these as they also interfered.

I will clean it up and re run everything again (10th times a charm) and report back. The pipeline has been changed a little since I ran them, so hopefully it will work now.

I think it is a problem that if one participant is not processed correctly that the qc outputs are not produced for any participants.

**Comment by josephdviviano** [comment]
Yes this is a known issue of sorts. Low priority to fix since it happens rarely unless something serious is wrong with the data. Anyhow if they data are running to completion and *arent* messed up you could just QC them by eye and/or just go ahead and analyze, the QC stuff isn't mandatory.

**Comment by s-lavoie** [comment]
I cleaned it up reran everything. I am still getting the same result. Here is the error again:

 File "/usr/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_wm_ero.nii.gz'
: No such file or directory
Generating 4D file dimensions for BEBASD
ls: cannot access /srv/MRI/WORKING/BEBASD/201//old_pipelinefile//*/: No such file or directory
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
Wrote data to /srv/MRI/WORKING/BEBASD/qc_NIFTI_overview.csv
Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epi-qc-spectra", line 366, in <module>
    regressor_spectra(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "/srv/CODE/epitome/bin/epi-qc-spectra", line 248, in regressor_spectra
    'PARAMS/global_mean.' + str(uid) + '.01.1D'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1333, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 147, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 496, in open
    raise IOError("%s not found." % path)
IOError: /srv/MRI/WORKING/BEBASD/118/TASK/SESS01/PARAMS/global_mean.SL_DISS_APR2.01.1D not found.



Really, the most important thing is for me to get the motion now.

**Comment by josephdviviano** [comment]
What is this folder?
 
    /srv/MRI/WORKING/BEBASD/201//old_pipelinefile

This does not follow convention.

**Comment by josephdviviano** [comment]
You might need to consult the documentation on how an epitome directory structure is supposed to look. You shouldn't have other junk in there. I can confirm that the motion plotting code works so long as all of the subjects made it through to the motion correction stage.

I think Aman might need to help you.

**Comment by josephdviviano** [comment]
I'm in your experiment now and I can see you have lots of folders in the directory structure that shouldn't be there. Example:

/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/old_processing

1) Move ALL of these folders somewhere else (like /srv/analysis).
2) Delete *everything* except for the input files and run the pipeline again. The pipeline itself is failing because your directory structure is wrong.

**Comment by s-lavoie** [comment]
Hi, I removed it and just have the run folders. I am still getting these errors:

IOError: [Errno 2] No such file or directory: '/srv/MRI/WORKING/BEBASD/118/TASK/SESS01/anat_wm_ero.nii.gz'
: No such file or directory
Generating 4D file dimensions for BEBASD
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
ERROR: Could not open file
Wrote data to /srv/MRI/WORKING/BEBASD/qc_NIFTI_overview.csv
Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epi-qc-spectra", line 366, in <module>
    regressor_spectra(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
  File "/srv/CODE/epitome/bin/epi-qc-spectra", line 248, in regressor_spectra
    'PARAMS/global_mean.' + str(uid) + '.01.1D'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1333, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 147, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 496, in open
    raise IOError("%s not found." % path)
IOError: /srv/MRI/WORKING/BEBASD/118/TASK/SESS01/PARAMS/global_mean.SL_DISS_APR2.01.1D not found.

**Comment by josephdviviano** [comment]
Also, `qc_spectra` is broken at the moment due to changes i made to the filter module. don't bother running that (it is extremely experimental anyhow and not of use to you).

Why are you trying to run qc_spectra?

**Comment by s-lavoie** [comment]
Dale and I decided to run all the qc checks. The most important at the moment is the masks and the motion. I am fine without getting the spectra to work, but would like to get the motion qc working.

**Comment by josephdviviano** [comment]
The motion QC should work. Those errors are from other QCs.

**Comment by s-lavoie** [comment]
The motion qc file isn't even being produced though

**Comment by josephdviviano** [comment]
Run the motion qc command in isolation and post what it gives you. You are posting something else.

**Comment by josephdviviano** [comment]
There does appear to be something wrong with motionind, but it isn't related to the stuff you posted above.

**Comment by s-lavoie** [comment]
I tried, and it came up with this:

: No such file or directory

**Comment by josephdviviano** [comment]
OK this is a bug. I'll fix it tomorrow hopefully.

**Comment by josephdviviano** [comment]
Thanks for your patience with this.

**Comment by josephdviviano** [comment]
OK thanks for helping me track down this bug. Somehow the file I was working with was edited on windows ?? (windows and unix text files are not compatible with one another). I'm not sure if I did this because I'm never on windows anymore. I wonder if it is possible I pulled one of Aman's pull requests by mistake. Not clear how that could have happened but it is fixed now. 

@aigoyal please pull the latest updates.

**Comment by aigoyal** [comment]
The pipeline on harford is now current with Joseph's latest.

**Comment by s-lavoie** [comment]
I tried to run the motion qc and it is still not working. I think it is because I have an issue with one participant. I am getting this error: IOError: /srv/MRI/WORKING/BEBASD/226/TASK/SESS01/PARAMS/motion.SL_DISS_APR2.06.1D not found.

I tried removing all the processed data form this participant and rerunning them, but they still do not produce this file. 
Will I need to remove them from the working directory, just to produce the motion qc file???

**Comment by josephdviviano** [comment]
yes. you have subjects in your experiment directory that aren't being pre-processed properly, so you have bigger problems than the QC plot.
